### ISSUE TITLE
Code Structure Review (from Reddit)

### ISSUE THREAD

**Issue by RadicalZephyr** [ozkar99/cm-telemetry#1]
Hey, I thought responding here might make more sense than on Reddit.

Looking a little more closely at your code, it seems like you have a lot of file/folder structure for not very much code.  Given your project it seems like you are planning to add support for a lot more games.  I think the `dirt` module makes sense in that case, but there are a few ways you could make the structure more idiomatic.

Using the `mod.rs` filename style is a bit of a legacy thing. The newer style is to use `dirt.rs` in the root of `src/`.  Also, it's very strange to me that you have a module named `dirt::dirt`, I would just put the contents of `dirt/dirt.rs` into `dirt.rs` and then keep the event submodule if you want. I would likely put the event stuff directly in the dirt module so that you can have fewer folders.

If you want a bit more structure, I might make a root `games` module, and then make the code for each game a submodule of that, so it would become `games/dirt.rs`.

I also think the content of net.rs could just be in lib.rs.  It looks like you've done a lot of Ruby and Go before this.  I know Rubyists tend to prefer shorter files with one type per file, but part of that is because Ruby code is hard to refactor. One of the benefits of Rusts type system is that refactoring is much safer, and having more code in one file tends to be less of a problem.  You also end up needing to write more types often, and sometimes they are only for use internally to the module where they are defined. The heuristic I use is to make one module per "concept" that typically exports only one or two types to be used by other modules.

In general it's pretty unusual to see a module that has no code in it that just declares submodules, it just adds extra files for no real benefit.  One thing that you may not be aware of regarding `use` statements inside a single crate.  You can import any type from any module and two modules can import types from each other, `rustc` will resolve it all just fine.  So there's no need to introduce module structure to make imports more consistent or make them work or anything.

Let me know if you have any specific questions about these thoughts, it looks like a good start though! And welcome to Rust! It's a great language and a pretty great community, come join us on the [official community spaces](https://www.rust-lang.org/community).

**Comment by ozkar99** [comment]
Hey @RadicalZephyr thanks for all the feedback and the warm welcome!

I do plan adding more games supported, thanks for commenting on the newer style of modules, i knew that `mod.rs` was legacy but i couldn't really find how to use the new style on the documentation.

A lot of the things you mention like having a `games` module is something that i have planed, but right now i am struggling with the implementation due to my lack of understanding of the rust module system.

Ill try to refactor during the weekend, and will update this task if any specific issues arise.

Again, thanks for the feedback, appreciate it :)

**Comment by ozkar99** [comment]
bumped the create to 1.0 since this breaks previous usage (sure...) and re-factored a bit more towards how i envisioned the structure from the beginning.

Also scrapped the idea of a `games` module since every game should be its public module.

If you have time let me know if you have more comments regarding https://github.com/ozkar99/cm-telemetry/commit/025100ced085efc314decc206d7831e0cc458595 

In the mantime i'll close the issue as a "no preassure" kind of thing, meaning: feel free stop answering my questions anytime its unreasonable of me to expect people to give up their time babysitting my educational projects.

P.S.
i see you are into clojure and racket, coming from the other end of the func prog spectrum (haskell), the type system is what got  me into rust.

**Comment by RadicalZephyr** [comment]
Heh, no worries, I enjoy reviewing code and it's a more productive way to procrastinate than scrolling reddit.

The type system is also a big part of what brought me to Rust!  It's such a pragmatic language, where you can write nice functional idioms but also get really precise control over how memory is used!  I sometimes want to be able to work at a slightly higher level where I can just have a GC and toss around references to everything, but I would want that to integrate really nicely with Rust. My (pipe) dream language is porting Clojure to be hosted on Rust. One day...
